### ISSUE TITLE
NICE!

### ISSUE THREAD

**Issue by rolinger** [vin-ni/hover-on-touch#2]
I was just looking for how to do a 'hover' event on a mobile platform....yours solution looks like exactly what I need.  Gonna load it and test it out now.  Thanks for sharing this!

I need to do popups for long button presses.

**Comment by rolinger** [comment]
hmmm...a bit more searching and I see `onTouch` events for mobile devices.  If that doesn't work then I am using your code.

**Comment by vin-ni** [comment]
How did it turn out?

**Comment by rolinger** [comment]
My app is using Ionic v1.  Turns out Ionic has its own on-hold & on-release functions so I went with its built in features.  I tried installing Angular ngTouch but I couldn't get it to work, was about to move back to your solution when I discovered the Ionic feature.
